anatomy_config:
  iri_accession: 99999
  iri_prefix: http://purl.obolibrary.org/obo/XPO_
  global:
    blacklist:
      - http://purl.obolibrary.org/obo/XAO_0003003
      - http://purl.obolibrary.org/obo/XAO_0000000
    blacklist_branch:
      - http://purl.obolibrary.org/obo/XAO_0003185
      - http://purl.obolibrary.org/obo/XAO_1000000
  patterns:
    - pattern: abnormalAbsenceOfAnatomicalEntity
      blacklist:
      - http://purl.obolibrary.org/obo/XAO_0005200
      - http://purl.obolibrary.org/obo/XAO_0005201
      - http://purl.obolibrary.org/obo/XAO_0005203
      - http://purl.obolibrary.org/obo/XAO_0005204
      - http://purl.obolibrary.org/obo/XAO_0005212
      blacklist_branch:
      - http://purl.obolibrary.org/obo/XAO_0003007
      - http://purl.obolibrary.org/obo/XAO_0005205
    - pattern: mislocalisedAnatomicalEntity
      blacklist:
      - http://purl.obolibrary.org/obo/XAO_0005200
      - http://purl.obolibrary.org/obo/XAO_0005201
      - http://purl.obolibrary.org/obo/XAO_0005203
      - http://purl.obolibrary.org/obo/XAO_0005204
      - http://purl.obolibrary.org/obo/XAO_0005212
      blacklist_branch:
      - http://purl.obolibrary.org/obo/XAO_0003007
      - http://purl.obolibrary.org/obo/XAO_0005205
    - pattern: abnormallyDecreasedSizeOfAnatomicalEntity
      blacklist:
      - http://purl.obolibrary.org/obo/XAO_0005200
      - http://purl.obolibrary.org/obo/XAO_0005201
      - http://purl.obolibrary.org/obo/XAO_0005203
      - http://purl.obolibrary.org/obo/XAO_0005204
      - http://purl.obolibrary.org/obo/XAO_0005212
      blacklist_branch:
      - http://purl.obolibrary.org/obo/XAO_0003007
      - http://purl.obolibrary.org/obo/XAO_0005205
    - pattern: abnormallyIncreasedSizeOfAnatomicalEntity
      blacklist:
      - http://purl.obolibrary.org/obo/XAO_0005200
      - http://purl.obolibrary.org/obo/XAO_0005201
      - http://purl.obolibrary.org/obo/XAO_0005203
      - http://purl.obolibrary.org/obo/XAO_0005204
      - http://purl.obolibrary.org/obo/XAO_0005212
      blacklist_branch:
      - http://purl.obolibrary.org/obo/XAO_0003007
      - http://purl.obolibrary.org/obo/XAO_0005205
    - pattern: abnormalAnatomicalEntity
      blacklist:
      blacklist_branch:
        - http://purl.obolibrary.org/obo/XAO_1000000
